[project]
name = "todo-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.124.0",
    "psycopg2-binary>=2.9.11",
    "rich",
    "sqlalchemy>=2.0.44",
    "typer",
    "uvicorn[standard]>=0.38.0",
]
